# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('is_deleted', models.BooleanField(default=False)),
                ('body', models.TextField(blank=True, help_text='*** Be careful pasting from Word.', null=True)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('has_emailed', models.BooleanField(default=False)),
                ('views', models.IntegerField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, help_text='all lowercase, dashes and no spaces!', max_length=100, null=True, unique=True)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Post',
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('is_deleted', models.BooleanField(default=False)),
                ('slug', models.CharField(blank=True, help_text='all lowercase, dashes and no spaces!', max_length=100, null=True, unique=True)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Post Tag',
                'db_table': 'post_tag',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, db_table='post_tag_map', to='blog.PostTag'),
        ),
    ]
